"""empty message

Revision ID: fab7596fd329
Revises: 
Create Date: 2022-08-18 08:44:48.564273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fab7596fd329'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('original_uploaded_file_name', sa.String(length=255), nullable=True),
    sa.Column('uploaded_file_name', sa.String(length=255), nullable=True),
    sa.Column('output_yaml_file_name', sa.String(length=255), nullable=True),
    sa.Column('output_yaml_file_path', sa.String(length=255), nullable=True),
    sa.Column('output_pdf_file_name', sa.String(length=255), nullable=True),
    sa.Column('output_pdf_file_path', sa.String(length=255), nullable=True),
    sa.Column('param_output_format', sa.String(length=255), nullable=True),
    sa.Column('param_frame_rate', sa.Float(precision=2), nullable=True),
    sa.Column('param_is_exif_info_captured', sa.Boolean(), nullable=True),
    sa.Column('output_exif_file_name', sa.String(length=255), nullable=True),
    sa.Column('output_exif_file_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_conversions')
    op.drop_table('users')
    # ### end Alembic commands ###
